# Generated by Django 3.0.4 on 2020-03-13 14:05

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0018_auto_20200302_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('employee_attendance_objects', picklefield.fields.PickledObjectField(default=list, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('check_in_toggle', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(default=None)),
                ('check_out_time', models.DateTimeField(default=None)),
                ('in_time', models.DateTimeField(default=None)),
                ('out_time', models.DateTimeField(default=None)),
                ('is_late', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance', to='employee_management.Employee')),
            ],
        ),
    ]
