# Generated by Django 3.0.3 on 2020-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0002_auto_20200313_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
