# Generated by Django 3.0.3 on 2020-03-13 15:16

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0003_dailyattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee_attendance_objects',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
