# Generated by Django 3.0.3 on 2020-03-16 08:37

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0004_auto_20200313_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee_attendance_objects',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
