# Generated by Django 3.0.3 on 2020-03-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0005_auto_20200316_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='name',
        ),
    ]
