# Generated by Django 3.0.3 on 2020-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0007_auto_20200318_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='firm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
