# Generated by Django 3.0.3 on 2020-02-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
