# Generated by Django 3.0.3 on 2020-02-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0002_auto_20200221_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
