# Generated by Django 3.0.3 on 2020-02-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0003_auto_20200221_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
