# Generated by Django 3.0.3 on 2020-02-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0004_customallowance_customdeduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdeduction',
            name='employee',
        ),
    ]
