# Generated by Django 3.0.3 on 2020-02-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0005_remove_customdeduction_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdeduction',
            name='employee',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
