# Generated by Django 3.0.3 on 2020-02-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0006_customdeduction_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customallowance',
            name='employee',
        ),
    ]
