# Generated by Django 3.0.3 on 2020-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0007_remove_customallowance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customallowance',
            name='employee',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
