# Generated by Django 2.2.5 on 2020-03-01 17:41

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0008_customallowance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='all_allowances',
            field=picklefield.fields.PickledObjectField(default={}, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='all_deductions',
            field=picklefield.fields.PickledObjectField(default={}, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='all_taxation',
            field=picklefield.fields.PickledObjectField(default={}, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='basic_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='nhif',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='nssf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='relief',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=picklefield.fields.PickledObjectField(default='Update', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='taxable',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_allowances',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customallowance',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customdeduction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
