# Generated by Django 2.2.5 on 2020-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0009_auto_20200301_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='paye',
            field=models.FloatField(default=0),
        ),
    ]
