# Generated by Django 2.2.5 on 2020-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0010_payslip_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='tax_charged',
            field=models.FloatField(default=0, null=True),
        ),
    ]
