# Generated by Django 3.0.3 on 2020-03-26 15:57

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0011_payslip_tax_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='all_allowances',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='all_deductions',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='all_taxation',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
