# Generated by Django 3.0.3 on 2020-03-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200302_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.users',),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
