# Generated by Django 3.0.3 on 2020-03-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authentication', '0003_auto_20200326_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='UserEmployee',
        ),
    ]
