# Generated by Django 3.0.3 on 2020-02-10 09:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_type', models.CharField(max_length=15)),
                ('base_salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('firm_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('home_address', models.TextField(max_length=50)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +11111111111', regex='^\\+?1?\\d{9,13}$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('kra_pin', models.CharField(max_length=30, unique=True)),
                ('nhif_number', models.TextField(unique=True)),
                ('nssf_number', models.TextField(unique=True)),
                ('department', models.CharField(max_length=20)),
                ('is_manager', models.BooleanField()),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_contract', to='employee_management.Contract')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='employee_management.Firm')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_education', to='employee_management.Employee')),
            ],
        ),
    ]
