# Generated by Django 3.0.3 on 2020-02-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_auto_20200210_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_contract', to='employee_management.Contract'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='employee_management.Firm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
