# Generated by Django 3.0.3 on 2020-02-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_auto_20200212_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_contract', to='employee_management.Contract'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='employee_management.Firm'),
        ),
    ]
