# Generated by Django 3.0.3 on 2020-02-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_auto_20200212_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='employee_management.Firm'),
        ),
    ]
