# Generated by Django 3.0.3 on 2020-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_auto_20200212_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employee_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
