# Generated by Django 3.0.3 on 2020-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_contract_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='identification_number',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
