# Generated by Django 3.0.3 on 2020-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0008_auto_20200218_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
