# Generated by Django 2.2.5 on 2020-03-02 13:57

from django.db import migrations, models
import employee_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0010_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='files',
            field=models.FileField(default=None, upload_to=employee_management.models.document_file_path),
            preserve_default=False,
        ),
    ]
