# Generated by Django 2.2.5 on 2020-03-02 15:54

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0011_education_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=picklefield.fields.PickledObjectField(default=[], editable=False, null=True),
        ),
    ]
