# Generated by Django 2.2.5 on 2020-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0012_auto_20200302_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
