# Generated by Django 2.2.5 on 2020-03-02 17:17

from django.db import migrations, models
import employee_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0014_auto_20200302_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='files',
            field=models.FileField(upload_to=employee_management.models.education_file_path),
        ),
    ]
