# Generated by Django 2.2.5 on 2020-03-02 17:29

from django.db import migrations, models
import employee_management.models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0015_auto_20200302_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('files', models.FileField(upload_to=employee_management.models.document_file_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=picklefield.fields.PickledObjectField(default=[], editable=False, null=True),
        ),
    ]
