# Generated by Django 2.2.5 on 2020-03-02 17:39

from django.db import migrations, models
import employee_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0016_auto_20200302_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(null=True, upload_to=employee_management.models.logo_file_path),
        ),
    ]
