# Generated by Django 2.2.5 on 2020-03-02 18:48

from django.db import migrations, models
import django.db.models.deletion
import employee_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0017_firm_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to=employee_management.models.logo_file_path)),
                ('website', models.URLField()),
                ('mailing_addrss', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='firm',
            name='logo',
        ),
        migrations.AddField(
            model_name='firm',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='firm_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_profile', to='employee_management.FirmProfile'),
        ),
    ]
