# Generated by Django 3.0.3 on 2020-03-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0018_auto_20200302_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmprofile',
            old_name='mailing_addrss',
            new_name='mailing_address',
        ),
    ]
