# Generated by Django 3.0.3 on 2020-03-21 18:33

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0019_auto_20200318_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='allowances',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False, null=True),
        ),
    ]
