# Generated by Django 3.0.3 on 2020-03-22 12:56

from django.db import migrations, models
import employee_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0020_contract_allowances'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=employee_management.models.temp_file_path)),
            ],
        ),
    ]
